version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/studio"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
