name: Scheduled Build

on:
  schedule:
    # Runs at midnight and midday every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build hook request
        run: curl -X POST -d {} ${{ secrets.BUILD_HOOK }}
